services:
  - type: web
    region: ohio
    name: sample-service-name
    env: python
    buildCommand: "./render_build.sh"
    startCommand: "gunicorn src.wsgi:application"   # <- sin --chdir y usando src.wsgi
    plan: free
    numInstances: 1
    envVars:
      - key: VITE_BASENAME
        value: /
      - key: FLASK_APP
        value: src.app                        # <- módulo, no ruta de archivo
      - key: FLASK_DEBUG
        value: 0
      - key: FLASK_APP_KEY
        value: "any key works"
      - key: PYTHON_VERSION
        value: 3.10.6
      - key: DATABASE_URL
        fromDatabase:
          name: postgresql-trapezoidal-42170
          property: connectionString

databases:
  - name: postgresql-trapezoidal-42170
    region: ohio
    ipAllowList: []
    plan: free